title:            Are We VR yet?
description:      "Follow the progress of VR in the web"
author: Diego Marcos
author_email: diego.marcos@gmail.com
exclude: ["README.md"]
url: http://www.arewevryet.com/
baseurl:
